@startuml
!include <C4/C4_Container.puml>
!include <C4/C4_Component.puml>

System_Boundary(jlsBoundry, "John Lennon's Store Software System") {
  Container(ui, "UI", "C#, .NET", \
  "App di User Interface per gestione crenziali utente") #609EDB

  Container_Boundary(backend, "Backend") {
    Component(crudController, "CRUD Controller","Component", \
    "Insieme di operazioni del Controller per CRUD su utenti")

    Component(crudServices, "Servizi per CRUD",".NET,C#", \
    "Insieme di servizi per la gestione delle operazioni CRUD") 
  
    Component(crudRepository, "CRUD Repository",".NET,C#", \
    "Repository per comunicazione con Database")
  }

  database "User Database\nContiene le anagrafiche utenti" as usersDb
  skinparam databaseBackgroundColor #333333
  skinparam databaseFontColor #FFFFFF

  Rel(ui,crudController,"Chiamata API a", "HTTPS")
  Rel(crudController,crudServices,"Invia operazione a","C#,.NET (?)")
  Rel(crudServices,crudRepository,"Invio richiesta a", "C#,.NET (?)")
  Rel(crudRepository,usersDb,"Chiamata a","MySQL")
}
@enduml