services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: jlstore-mssql
    restart: unless-stopped
    ports: ["1433:1433"]
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: "Developer"
    volumes:
      - mssqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$${MSSQL_SA_PASSWORD}\" -C -Q \"SELECT 1\" || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  devcert-init:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    environment:
      CERT_PASSWORD: "${CERT_PASSWORD}"
    command: >
      bash -lc '
        set -euo pipefail
        mkdir -p /https
        rm -f /https/aspnetapp.pfx
        dotnet dev-certs https -ep /https/aspnetapp.pfx -p "$CERT_PASSWORD" -q
        if ! openssl pkcs12 -in /https/aspnetapp.pfx -passin pass:"$CERT_PASSWORD" -nokeys -clcerts >/dev/null 2>&1; then
          echo "ERRORE: PFX non apribile con la password fornita"; exit 1
        fi
        chmod 644 /https/aspnetapp.pfx
        ls -l /https
      '
    volumes:
      - devcerts:/https
    restart: "no"

  jlstore-app:
    build:
      context: ./JLStore
      dockerfile: Containerfile
    container_name: jlstore-app
    depends_on:
      mssql:
        condition: service_healthy
      devcert-init:
        condition: service_completed_successfully
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:7250;http://+:5250"
      ASPNETCORE_HTTPS_PORTS: "7250"
      ASPNETCORE_HTTP_PORTS: "5250"
      ConnectionStrings__Default: "Server=mssql,1433;Database=jlstore;User Id=sa;Password=${MSSQL_SA_PASSWORD};Encrypt=True;TrustServerCertificate=True;MultipleActiveResultSets=True"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "${CERT_PASSWORD:-devcert}"
    volumes:
      - devcerts:/https:ro
    ports:
      - "5250:5250"
      - "7250:7250"
    restart: unless-stopped

volumes:
  mssqldata:
  devcerts:
