version: "3.9"

x-app-base: &app-base
  build:
    context: ./JLStore
    dockerfile: Containerfile
  environment:
    ASPNETCORE_ENVIRONMENT: "Development"
    ASPNETCORE_URLS: "http://+:5250"   # <-- SOLO HTTP
    DOTNET_RUNNING_IN_CONTAINER: "true"
  ports:
    - "5250:5250"
  restart: unless-stopped

services:
  # === MSSQL PROFILE =========================================================
  mssql:
    profiles: ["mssql"]
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: jlstore-mssql
    command: ["/opt/mssql/bin/sqlservr", "-T272"]
    ports: ["1433:1433"]
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD:-StrongPassw0rd!}"
    volumes:
      - mssqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$${MSSQL_SA_PASSWORD}\" -C -Q \"SELECT 1\" || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped

  jlstore-app-mssql:
    profiles: ["mssql"]
    <<: *app-base
    container_name: jlstore-app-mssql
    depends_on:
      mssql:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:5250"
      DOTNET_RUNNING_IN_CONTAINER: "true"

      DB_PROVIDER: "sqlserver"
      ConnectionStrings__Default: "Server=mssql,1433;Database=jlstore;User Id=sa;Password=${MSSQL_SA_PASSWORD:-StrongPassw0rd!};Encrypt=True;TrustServerCertificate=True;MultipleActiveResultSets=True"

  # === POSTGRES PROFILE ======================================================
  postgres:
    profiles: ["postgres"]
    image: postgres:16
    container_name: jlstore-postgres
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: "jlstore"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-mysecretpassword}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped

  jlstore-app-postgres:
    profiles: ["postgres"]
    <<: *app-base
    container_name: jlstore-app-postgres
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:5250"
      DOTNET_RUNNING_IN_CONTAINER: "true"

      DB_PROVIDER: "postgres"
      ConnectionStrings__Default: "Host=postgres;Port=5432;Database=jlstore;Username=postgres;Password=${POSTGRES_PASSWORD:-mysecretpassword};SSL Mode=Prefer;Trust Server Certificate=true"
      
volumes:
  mssqldata:
  pgdata:
